"""Initial dbgit_meta schema

Revision ID: 2878feb5df3a
Revises: 
Create Date: 2026-04-27 17:25:58.585517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2878feb5df3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # create schema if not exists
    op.execute("CREATE SCHEMA IF NOT EXISTS dbgit_meta")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diffs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_commit_hash', sa.String(length=64), nullable=True),
    sa.Column('to_commit_hash', sa.String(length=64), nullable=True),
    sa.Column('table_name', sa.Text(), nullable=True),
    sa.Column('diff_type', sa.String(length=20), nullable=True),
    sa.Column('diff_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count_added', sa.Integer(), nullable=False),
    sa.Column('row_count_removed', sa.Integer(), nullable=False),
    sa.Column('row_count_modified', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='dbgit_meta'
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dbgit_meta'
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='dbgit_meta'
    )
    op.create_table('tracked_databases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connection_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='dbgit_meta'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='dbgit_meta'
    )
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('head_commit_hash', sa.String(length=64), nullable=True),
    sa.Column('base_commit_hash', sa.String(length=64), nullable=True),
    sa.Column('created_from_branch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['created_from_branch_id'], ['dbgit_meta.branches.id'], ),
    sa.ForeignKeyConstraint(['database_id'], ['dbgit_meta.tracked_databases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbgit_meta'
    )
    op.create_table('user_database_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['dbgit_meta.tracked_databases.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['dbgit_meta.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dbgit_meta.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'database_id', 'role_id'),
    schema='dbgit_meta'
    )
    op.create_table('commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('parent_hash', sa.String(length=64), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('database_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tables_affected', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_merge_commit', sa.Boolean(), nullable=False),
    sa.Column('merge_source_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['dbgit_meta.users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['dbgit_meta.branches.id'], ),
    sa.ForeignKeyConstraint(['database_id'], ['dbgit_meta.tracked_databases.id'], ),
    sa.ForeignKeyConstraint(['parent_hash'], ['dbgit_meta.commits.hash'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    schema='dbgit_meta'
    )
    op.create_table('data_pull_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_branch_id', sa.UUID(), nullable=True),
    sa.Column('target_branch_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merge_commit_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['dbgit_meta.users.id'], ),
    sa.ForeignKeyConstraint(['database_id'], ['dbgit_meta.tracked_databases.id'], ),
    sa.ForeignKeyConstraint(['source_branch_id'], ['dbgit_meta.branches.id'], ),
    sa.ForeignKeyConstraint(['target_branch_id'], ['dbgit_meta.branches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbgit_meta'
    )
    op.create_table('change_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commit_hash', sa.String(length=64), nullable=True),
    sa.Column('operation', sa.String(length=10), nullable=False),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('schema_name', sa.Text(), nullable=False),
    sa.Column('row_pk', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_columns', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('sequence_num', sa.BigInteger(), nullable=False),
    sa.Column('lsn', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['commit_hash'], ['dbgit_meta.commits.hash'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbgit_meta'
    )
    op.create_table('pr_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pr_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['dbgit_meta.data_pull_requests.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['dbgit_meta.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbgit_meta'
    )
    op.create_table('schema_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('database_id', sa.UUID(), nullable=True),
    sa.Column('commit_hash', sa.String(length=64), nullable=True),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('schema_ddl', sa.Text(), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commit_hash'], ['dbgit_meta.commits.hash'], ),
    sa.ForeignKeyConstraint(['database_id'], ['dbgit_meta.tracked_databases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbgit_meta'
    )
    op.create_table('snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commit_hash', sa.String(length=64), nullable=True),
    sa.Column('database_id', sa.UUID(), nullable=True),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('snapshot_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('storage_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['commit_hash'], ['dbgit_meta.commits.hash'], ),
    sa.ForeignKeyConstraint(['database_id'], ['dbgit_meta.tracked_databases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbgit_meta'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshots', schema='dbgit_meta')
    op.drop_table('schema_versions', schema='dbgit_meta')
    op.drop_table('pr_reviews', schema='dbgit_meta')
    op.drop_table('change_events', schema='dbgit_meta')
    op.drop_table('data_pull_requests', schema='dbgit_meta')
    op.drop_table('commits', schema='dbgit_meta')
    op.drop_table('user_database_roles', schema='dbgit_meta')
    op.drop_table('branches', schema='dbgit_meta')
    op.drop_table('users', schema='dbgit_meta')
    op.drop_table('tracked_databases', schema='dbgit_meta')
    op.drop_table('roles', schema='dbgit_meta')
    op.drop_table('outbox_events', schema='dbgit_meta')
    op.drop_table('diffs', schema='dbgit_meta')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS dbgit_meta CASCADE")
